### ISSUE TITLE
Error with one specific code

### ISSUE THREAD

**Issue by st501351** [warint/statcanR#1]
for me 
`does.not.work <- statcan_data("10-10-0139-01", "eng")`

while 

`works.fine <- statcan_data("36-10-0105-01", "eng")`

First one worked a few weeks ago and now gives the error message Error in read.table(file = file, header = header, sep = sep, quote = quote,  :   duplicate 'row.names' are not allowed

**Comment by tsenegas** [comment]
Hi,

It seems that there is a problem with some metadata tables. 

We have solved the problem. Try to uninstall the statcanR package and make a new installation via devtools. You should now have version 0.2.2.9000.

The problem is solved and statcan_data("10-10-0139-01", "eng") should work normally.

Let us know if you encounter this problem again.

Thanks

**Comment by st501351** [comment]
Perfect, thank you!

**Comment by warint** [comment]
Thank YOU! 😀
